//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarcinSzymanski.Lifereg.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarcinSzymanski.Lifereg.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string SError {
            get {
                return ResourceManager.GetString("SError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No censoring indicator values provided.
        /// </summary>
        internal static string SErrorNoCensor {
            get {
                return ResourceManager.GetString("SErrorNoCensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No model type selected.
        /// </summary>
        internal static string SErrorNoModelType {
            get {
                return ResourceManager.GetString("SErrorNoModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No target variable.
        /// </summary>
        internal static string SErrorNoTarget {
            get {
                return ResourceManager.GetString("SErrorNoTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lower variable selected.
        /// </summary>
        internal static string SErrorNoTargetLower {
            get {
                return ResourceManager.GetString("SErrorNoTargetLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No upper variable selected.
        /// </summary>
        internal static string SErrorNoTargetUpper {
            get {
                return ResourceManager.GetString("SErrorNoTargetUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be numeric.
        /// </summary>
        internal static string SErrorNumeric {
            get {
                return ResourceManager.GetString("SErrorNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survival analysis.
        /// </summary>
        internal static string STaskCategory {
            get {
                return ResourceManager.GetString("STaskCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIFEREG Task.
        /// </summary>
        internal static string STaskDescription {
            get {
                return ResourceManager.GetString("STaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIFEREG.
        /// </summary>
        internal static string STaskName {
            get {
                return ResourceManager.GetString("STaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string STreeNodeData {
            get {
                return ResourceManager.GetString("STreeNodeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model specification.
        /// </summary>
        internal static string STreeNodeModel {
            get {
                return ResourceManager.GetString("STreeNodeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string STreeNodeOptions {
            get {
                return ResourceManager.GetString("STreeNodeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string STreeNodeOutput {
            get {
                return ResourceManager.GetString("STreeNodeOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        internal static string STreeNodePlot {
            get {
                return ResourceManager.GetString("STreeNodePlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By variable.
        /// </summary>
        internal static string SVarBy {
            get {
                return ResourceManager.GetString("SVarBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classification variables.
        /// </summary>
        internal static string SVarClass {
            get {
                return ResourceManager.GetString("SVarClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect variables.
        /// </summary>
        internal static string SVarEffects {
            get {
                return ResourceManager.GetString("SVarEffects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Censor variable.
        /// </summary>
        internal static string SVarTargetCensor {
            get {
                return ResourceManager.GetString("SVarTargetCensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left censoring value.
        /// </summary>
        internal static string SVarTargetLower {
            get {
                return ResourceManager.GetString("SVarTargetLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response variable.
        /// </summary>
        internal static string SVarTargetResponse {
            get {
                return ResourceManager.GetString("SVarTargetResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right censoring value.
        /// </summary>
        internal static string SVarTargetUpper {
            get {
                return ResourceManager.GetString("SVarTargetUpper", resourceCulture);
            }
        }
    }
}
